version: "3.9"
services:
  db:
    image: postgres:12.8
    container_name: hackathon-db
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - ./src/sql/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hackathon
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=hackathon@fortna.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
  backend:
    image: 10.240.26.88:5000/fortna/hackathon-backend:latest
    container_name: hackathon-be
    restart: "no"
    ports:
      - 8088:8088
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - CONNECTION_URL=jdbc:postgresql://hackathon-db:5432/hackathon
      - CONNECTION_USERNAME=root
      - CONNECTION_PASSWORD=root
      - GAME_DIR=/data
    depends_on:
      - db
